gsl-lite/gsl-lite

- include/gsl/gsl-lite.h
> Removed superfluous ref.

- include/gsl/gsl-lite.h
You need a SFINAE disable for the implicit span<T> conversion from any type, else it is too greedy.
> Fix compile error with clang targeting MSVC.

- include/gsl/gsl-lite.h
- test/span.t.cpp
Fixes issue #25, allowing easily slicing off data until span is empty.
> Fix offset bounds check in subspan to allow creating empty subspans.

- README.md
- test/CMakeLists.txt
gsl-lite works with GCC 4.8.4 (it passes its tests, and works on our project, although we don't make a lot of use of it yet).
However, the CMake code for building the tests required some rearranging.
> Fix test compilation with GCC 4.8.4

- include/gsl/gsl-lite-vc6.h
- include/gsl/gsl-lite.h
- test/span.t.cpp
Microsoft Guideline Support Library has free-standing variant of as_bytes and as_writable_bytes. I have missed them switching from Microsoft GSL to gsl-lite(because of C++ standard downgrade).
> Free-standing functions: as_bytes, as_writable_bytes

- test/owner.t.cpp
- Fixed: tests memory leak detected by `-fsanitize=address` GCC option.
> Fixed memory leak, which prevents tests to pass with address sanitizing.

- include/gsl/gsl-lite.h
- test/CMakeLists.txt
- test/at.t.cpp
- test/lest_cpp03.hpp
- test/span.t.cpp
- test/string_span.t.cpp
Only two of the fixes were for GSL itself, but since all conversion warnings
have been fixed in the tests and these warnings have been enabled for the test
suite, it should be easier to discover conversion warnings in GSL in the future.
> Fix conversion and sign-conversion warnings.

- include/gsl/gsl-lite.h
- test/gsl-lite.t.h
- test/string_span.t.cpp
Following the behaviour described for `std::basic_string` [here](http://en.cppreference.com/w/cpp/string/basic_string/operator_ltltgtgt).
Unfortunately, I had to remove the specialised `string_span` printing implementation from the test suite as it would otherwise conflict.
> Support for output stream printing of string_span types via operator<<

- include/gsl/gsl-lite.h
With certain compilers (e.g. gcc 4.8.5), compiling with `-Wshadow` triggers a shadow warning on the local variables "first" and "last" in the `basic_string_span` constructor, because the shadow the "first" and "last" member functions, respectively:
```
In file included from test.cpp:1:0:
gsl/gsl-lite.h: In constructor ‘constexpr gsl::basic_string_span<T>::basic_string_span(gsl::basic_string_span<T>::pointer, gsl::basic_string_span<T>::pointer)’:
gsl/gsl-lite.h:1711:5: warning: declaration of ‘last’ shadows a member of 'this' [-Wshadow]
: span_( first, last )
^
gsl/gsl-lite.h:1711:5: warning: declaration of ‘first’ shadows a member of 'this' [-Wshadow]
```
This gets annoying real fast, since it shows up for every source file that ends up including gsl-lite.
This has already been fixed in …
> Fix -Wshadow warning

- include/gsl/gsl-lite.h
The `nullptr` in `not_null::get()` warns about C++11 keywords (`-Wc++11-compat`) on gcc for the cpp03 tests, and fails to compile with strict c++03 compatibility.
> Changed nullptr to gsl_nullptr in not_nul::get().

- include/gsl/gsl-lite.h
I added whatever constructors, destructors, move-copy operations needed to satisfy clang-tidy cppcoreguidelines tests, and added NOLINT to lines using reinterpret cast.
> Changes to pass clang-tidy cppcoreguidelines checks

- test/span.t.cpp
Some compilers resolve `uint32_t` to `long int` which then results in conversion error in `span`'s constructor when converting from `long int*` to `int*`.
I believe this has just been overseen.
> Fix potential conversion error

- include/gsl/gsl-lite.hpp
- test/gsl-lite.t.hpp
- test/lest_cpp03.hpp
- test/string_span.t.cpp
This compiler is GCC based and is targeting DOS. It does not support `wchar_t` nor `std::wstring` probably because there would not be much use of them in DOS.
All the tests and examples were tested on DOSBox and on FreeDOS using DJGPP for GCC 7.2.0 with success (actually there is one test failing in *cpp11 and in *cpp14 but you are probably aware of that).
Since DJGPP is a cross compiler, user has to supply cmake with `-DCMAKE_SYSTEM_NAME=Generic` to be able to build the project with it, see https://cmake.org/Wiki/CMake_Cross_Compiling.
Some relevant links regarding DJGPP cross compiler:
https://www.youtube.com/watch?v=yHrC_rZUaiA
https://github.com/andrewwutw/build-djgpp
> Introduce support for DJGPP cross compiler

- include/gsl/gsl-lite.hpp
The `size_in` parameter of the trivial `span` constructor is expected to be `0`, but not used otherwise. The parameter was therefore unused if `Expects` was elided. The new macro `gsl_EXPECTS_UNUSED_PARAM` makes the parameter unnamed in this case to fix the issue. Fixes #123
> Fix unused parameter in trivial span constructor if Expects elided

- include/gsl/gsl-lite.hpp
- test/util.t.cpp
Previously they would always take the error path, even when there is no exception in the guarded function. This is the reason why std::uncaught_exception was deprecated in favour of uncaught_exceptions, there's a paper about it here: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4152.pdf
I've added uncaught_exceptions for pre-2017 MSVC, GCC and Clang which is basically the same as the one used here: https://github.com/evgeny-panasyuk/stack_unwinding/blob/master/boost/exception/uncaught_exception_count.hpp
That version has been tested with a number of compiler versions.
> Fix final_action_return and final_action_error during stack unwinding

- include/gsl/gsl-lite.hpp
GCC didn't set the __cplusplus symbol correctly till version 4.7.0: https://stackoverflow.com/questions/2324658/how-to-determine-the-version-of-the-c-standard-used-by-the-compiler/7132549#7132549
> Workaround for misleading __cplusplus

- include/gsl/gsl-lite.hpp
Rename function parameter index to pos to eliminate warning link this:
```
gsl/gsl-lite.hpp: In function ‘constexpr T& gsl::at(gsl::span<T>, size_t)’:
gsl/gsl-lite.hpp:1109:62: warning: declaration of ‘index’ shadows a global declaration [-Wshadow]
gsl_api inline gsl_constexpr T & at( span<T> s, size_t index )
^
gsl/gsl-lite.hpp:573:36: note: shadowed declaration is here
typedef gsl_CONFIG_SPAN_INDEX_TYPE index;   // p0122r3 uses std::ptrdiff_t
```
> Rename function parameter index to pos

- include/gsl/gsl-lite.hpp
This also enables the usage of gsl::span objects in device code. The assert in the device code can easily be traced with `cuda-gdb`.
> Device code compatible fail_fast_assert

- include/gsl/gsl-lite.hpp
This should help reduce my warnings to that of only what is mine / stdlib ones when I use modules TS (that part I seem to not be able to control).
> Suppress more warnings I get from my project from this include.

- CMakeLists.txt
- README.md
- include/gsl/gsl-lite.hpp
This PR introduces the new macros `ExpectsAudit` and `EnsuresAudit` and the configuration macros `gsl_CONFIG_CONTRACT_LEVEL_AUDIT` and `gsl_CONFIG_CONTRACT_LEVEL_ASSUME` to implement audit-level and assume-level contract checking as proposed in #168.
It also deprecates the levels `gsl_CONFIG_CONTRACT_LEVEL_{EXPECTS|ENSURES}_ONLY` in favor of the new configuration macros `gsl_CONFIG_CONTRACT_{EXPECTS|ENSURES}_ONLY` which are orthogonal to the contract checking level.
Closes #168
Closes #70
> Add audit-level and assume-level contract checks

- include/gsl/gsl-lite.hpp
Up to now, only `__host__` `__device__` specifiers were
added with the gsl_api macro. `nvcc` also warns about
these function specifiers.
See also the discussion here:
https://stackoverflow.com/questions/46469062/warning-host-annotation-on-a-defaulted-function-is-ignored-why
Maybe you prefer to create an additional macro for defaulted functions.
> Remove function specifiers for defaulted functions

- include/gsl/gsl-lite.hpp
- test/gsl-lite.t.hpp
Some apple-clang compile errors are still not fixed, see comments in #133
> Fix compilation issues in current Travis builds

- test/CMakeLists.txt
- test/assert.t.cpp
- test/gsl-lite.t.hpp
Fix currently present gcc/clang warnings, and turn all warnings to errors.
Note: the comment relating to the warning in issue #195 is not modified in this PR, I leave that to @mbeutel, but the warning is fixed.
> Fix warnings

- .gitignore
- CMakeLists.txt
- README.md
- gsl-lite.natvis
- include/gsl/gsl-lite.hpp
- test/CMakeLists.txt
* Add CMake targets `gsl::gsl-lite-v0` and `gsl::gsl-lite-v1` which set versioned defaults.
* Add configuration option `gsl_CONFIG_INDEX_TYPE` which can be configured independently of `gsl_CONFIG_SPAN_INDEX_TYPE`, partly addressing #169.
> Add CMake targets for versioned defaults; add `gsl_CONFIG_INDEX_TYPE`

- CMakeLists.txt
- README.md
- conanfile.py
- include/gsl/gsl-lite.hpp
- test/not_null.t.cpp
- Fix versioned defaults in CMake
- Fix `gsl_CONFIG_TRANSPARENT_NOT_NULL` detection in tests
> Some fixes to versioned defaults and  `gsl_CONFIG_TRANSPARENT_NOT_NULL` tests

- include/gsl/gsl-lite.hpp
Use `gsl_HAVE_EXCEPTIONS` to disable any `throw` statements if no
exceptions are available, and to raise a compile-time error if
`gsl_CONFIG_CONTRACT_VIOLATION_THROWS` is defined without exceptions
available.
Fixes #216.
> Add `gsl_HAVE_EXCEPTIONS` feature-test macro

- include/gsl/gsl-lite.hpp
Use them to simplify the definition of `gsl::byte` in the sane case.
>  Add macros `gsl_DEFINE_ENUM_BITMASK_OPERATORS()` and `gsl_DEFINE_ENUM_RELATIONAL_OPERATORS()`

- README.md
- include/gsl/gsl-lite.hpp
- test/assert.t.cpp
Fixes a spurious static assertion for pre-/postcondition check arguments explicitly convertible to `bool` if `gsl_CONFIG_CONTRACT_CHECKING_OFF` is defined.
This PR also applies some minor formatting changes.
> Fix pre-/postcondition checks for contextually convertible types

- include/gsl/gsl-lite.hpp
The problem is that `gsl-lite.hpp` contains U+115F characters, but has no BOM.
And Visual Studio shows warning during compilation
warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
I believe these glyphs appeared in comments unintentionally.
> Fix compile issue due to \x115F unicode characters in comments

- test/CMakeLists.txt
Building GSL-Lite with GCC 4.7's almost, but not quite full C++11 support mode is the sole reason for the existence of the travis GCC 4.7 build and `gsl_HAVE( FUNCTION_REF_QUALIFIER )`. I do not know how I missed it when I added GCC 4.7. :D
> Allow C++11 on GCC 4.7

- include/gsl/gsl-lite.hpp
Fix issue #254.
Also, replaced some direct gsl_CONFIG_XXX instances with gsl_CONFIG( XXX )
> Fix issue #254: gsl_CONFIG_DEFAULTS_VERSION=1 does not compile without exceptions

- include/gsl/gsl-lite.hpp
> Improve diagnostic for calling `narrow<>()` without exceptions; avoid `narrow<>()` in gsl-lite

- include/gsl/gsl-lite.hpp
- test/span.t.cpp
Fixes #270, in which using this construct failed to compile in C++14 mode for gcc 5.4.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gsl-lite/gsl-lite/271)
> Span default constructor is now constexpr from C++11.

- include/gsl/gsl-lite.hpp
I found not_null_ic is not in the gsl_lite namespace.
Is this a mistake or deliberate ?
> add not_null_ic to gsl_lite namespace

- include/gsl/gsl-lite.hpp
* Add `gsl_STDLIB_CPPxx_OR_GREATER` macros to track standard library availability
* Add library feature detection macros `gsl_HAVE( HASH )`, `gsl_HAVE( MOVE_FORWARD )`
> Track language and library versions separately

- include/gsl/gsl-lite.hpp
- test/emulation.t.cpp
- test/gsl-lite.t.hpp
Avoid pulling in \<algorithm\>; provide our own implementation of `equal()` and `lexicographical_compare()`.
> Remove <algorithm> dependency

- include/gsl/gsl-lite.hpp
We only really need `std::reverse_iterator<>`, and that is provided indirectly through <array>.
> Remove <iterator> dependency

- include/gsl/gsl-lite.hpp
- test/issue.t.cpp
- test/span.t.cpp
> Add `std20::endian`, fix `byte` tests for big-endian architectures

- include/gsl/gsl-lite.hpp
- test/MakeTestTarget.cmake
- test/assert.t.cpp
- test/gsl-lite.t.hpp
- test/lest_cpp03.hpp
`gsl-lite` does not work out of the box with the NVHPC compilers on my system:
```
"include/gsl/gsl-lite.hpp", line 1394: error: identifier "__ORDER_LITTLE_ENDIAN__" is undefined
little = __ORDER_LITTLE_ENDIAN__,
^
"include/gsl/gsl-lite.hpp", line 1395: error: identifier "__ORDER_BIG_ENDIAN__" is undefined
big    = __ORDER_BIG_ENDIAN__,
^
"include/gsl/gsl-lite.hpp", line 1396: error: identifier "__BYTE_ORDER__" is undefined
native = __BYTE_ORDER__
^
```
This is a minimal patch to recognise the NVHPC compilers as distinct from GCC and assume little-endian order for them.
I tried to build and run the full set of `gsl-lite` tests and examples; there were no errors but a few warnings are repeated many times. For example:
```
"gsl-lite/test/not_null.t.cpp", line 694: warning: variable …
```
> Basic NVHPC compiler support.

- include/gsl/gsl-lite.hpp
- test/not_null.t.cpp
The `not_null<>` conversion operators previously made the unfounded and unnecessary assumption that the type being converted to is also pointer-like. This was a problem when converting `not_null<shared_ptr<T>>` to `weak_ptr<T>`, which is not pointer-like despite the name.
Also, the use of `gsl_Ensures()` in the member functions of `not_null<>` was misguided; these checks express class invariants, not postconditions, and should therefore be written using `gsl_Assert()`.
Fixes #310.
> Use `gsl_Assert()` for invariant checks; fix `weak_ptr<>` conversion

- include/gsl/gsl-lite.hpp
- test/emulation.t.cpp
These functions are required only for deprecated features of `span<>` and related classes. We do not want to commit to providing these forever as part of the public interface; therefore we put them in `gsl::detail` instead of  `gsl::std98`.
> Move `lexicographical_compare()`, `equal()` to `detail` namespace

- README.md
- include/gsl/gsl-lite.hpp
- test/not_null.t.cpp
- test/span.t.cpp
The result of a `make_shared<T>()` and `make_unique<T>()` can never be `nullptr`. So it makes sense for the *gsl-lite* version of these functions to return `not_null<shared_ptr<T>>` and `not_null<unique_ptr<T>>`.
This may be a breaking change for users of `gsl::make_unique<T>()`, which previously forwarded to `gsl::std14::make_unique<T>()`, which returned and still returns `unique_ptr<T>`. However, in most cases the change should not necessitate source code changes because `not_null<unique_ptr<T>>` implicitly converts to `unique_ptr<T>`.
> Add `gsl::make_unique<>()`, `gsl::make_shared<>()` which return `not_null<...>`

- README.md
- include/gsl/gsl-lite.hpp
- test/not_null.t.cpp
`gsl::is_valid()` permits explicitly checking for the moved-from state of `not_null<>`.
> Add `gsl::is_valid()`

- include/gsl/gsl-lite.hpp
libc++ can be configured not to support `wchar_t`. For example, the [open-source LLVM toolchain for 32bit ARM](https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm) is configured this way (refer to it's [CMakeLists.txt](https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/blob/fb3fb9358f90a49167332ff4abe41e0301cb0fe2/CMakeLists.txt#L398)). This PR sets `gsl_HAVE_WCHAR` correspondingly, allowing the library to be used in such toolchains.
> respect libc++ configuration option to disable wchar_t

- include/gsl/gsl-lite.hpp
* Add detection for `CONSTEXPR_23` language feature
* Add `gsl_constexpr23` which expands to `constexpr` if `gsl_HAVE( CONSTEXPR_23 )`, or to nothing otherwise
* Add `gsl_CPP23_OR_GREATER` and `gsl_STDLIB_CPP23_OR_GREATER`
* Add `std23` subnamespace
> Add tentative C++23 detection and `gsl_constexpr23`

- README.md
- include/gsl/gsl-lite.hpp
Rationale is explained in updates to README.md.
> Add `gsl_CONFIG_VALIDATES_UNENFORCED_CONTRACT_EXPRESSIONS` config switch

- README.md
- include/gsl/gsl-lite.hpp
"Removal" meaning "hiding behind feature flag" because we don't actually remove anything at all if we can help it.
For `string_span` removal, see #6; for `zstring_span` removal, see #282.
> Deprecate `string_span` and `zstring_span` and prepare for removal

- test/lest_cpp03.hpp
On at least GCC 13, on platforms where `char` is unsigned by default, checking if a `char`’s value is nonnegative by comparing to integer zero produced a warning which was treated as an error: “`comparison is always true due to limited range of data type [-Werror=type-limits]`”
Fixes #337.
> Cast char to signed to avoid type-limits warning

- README.md
- include/gsl/gsl-lite.hpp
- test/util.t.cpp
For modern (≥v1) defaults, avoid the polymorphic hierarchy beween the state classes. Do not touch the hierarchy for v0 defaults so as not to break binary compatibility.
For C++17 and greater, we no longer have to support movability thanks to guaranteed copy elision.
Closes #178, as this ticks the last box in the checklist.
> Improve `finally()`, `on_return()`, and `on_error()`

- include/gsl/gsl-lite.hpp
> Do not define member variables depending on C++ language support

- README.md
- azure-pipelines.yml
- include/gsl/gsl-lite.hpp
- test/not_null.t.cpp
Addresses shortcoming reported in https://github.com/gsl-lite/gsl-lite/issues/340#issuecomment-1830279289.
> Support `not_null<>` for `unique_ptr<void, D>` and `shared_ptr<void>`

- README.md
- azure-pipelines.yml
- include/gsl/gsl-lite.hpp
- test/util.t.cpp
Previously, calling `narrow<>()` from CUDA device code should have resulted
in a compile error but but did not due to a weird bug in NVCC pertaining to
the experimental "--expt-relaxed-constexpr" flag (cf. https://github.com/rapidsai/cudf/issues/7795).
This commit makes two changes to mitigate this problem:
(1) `narrow<>()` no longer responds to `gsl_CONFIG_CONTRACT_VIOLATION_THROWS`
because it does not do contract checking. Therefore, it plainly fails to
compile for `gsl_CONFIG( NARROW_THROWS_ON_TRUNCATION )` if exceptions are
unavailable (e.g. in device code).
(2) For `!gsl_CONFIG( NARROW_THROWS_ON_TRUNCATION )`, `narrow<>()` now makes
sure that the program is terminated by issuing a trap instruction if
`std::terminate()` is not available.
Also, `narrow_failfast<>()` now uses …
> Do not call `std::terminate()` in CUDA device code
