gsl-lite/gsl-lite

- include/gsl/gsl-lite.h
Fixed compilation problem on MSVC with disabled _HAS_CPP0X.
> Added check for _HAS_CPP0X

- include/gsl/gsl-lite.h
Also apparently the line endings are not consistent.
> Add const span::operator[]

- README.md
- include/gsl/gsl-lite.h
- test/at.t.cpp
- test/byte.t.cpp
- test/gsl-lite.t.h
- test/issue.t.cpp
- test/not_null.t.cpp
- test/span.t.cpp
- test/string_span.t.cpp
- test/t.bat
Thanks to Magnus Bergsten (@Sillamacka).
> Basic string span

- README.md
https://bintray.com/agauniyal/nonstd-lite/gsl-lite%3Anonstd-lite/0.26.0%3Astable
> Make v0.26.0 available in conan

- .travis.yml
- CMakeLists.txt
- README.md
- appveyor.yml
- cmake/PackageConfig.cmake.in
- example/01-basic.cpp
- example/02-span.cpp
- example/CMakeLists.txt
- example/cmake-pkg/01-use-gsl-pkg.py
- example/cmake-pkg/CMakeLists.txt
- example/cmake-pkg/main.cpp
- include/gsl/gsl-lite.hpp
- project/gsl-lite.cbp
- script/install-gsl-pkg.py
- script/update-version.py
- test/CMakeLists.txt
- test/gsl-lite.t.hpp
- test/t-all.bat
- test/t.bat
> CMake package configuration (updated)

- README.md
Outdated:
~~* Update CMake namespace from `gsl-lite::` to `gsl::`~~
~~* update versions from 0.29 to 0.33~~
> Add "As Conda package" section to README.md

- README.md
- conanfile.py
These two changes should probably be in different PRs but they are small changes that you may be happy to bring in together.
> Update conan package documentation

- include/gsl/gsl-lite.hpp
- zstring_span, wzstring_span, czstring_span, cwzstring_span added
- but I couldn't find proper usage of zstring_span
- unit tests are not added yet
> Add basic_zstring_span (martinmoene#136)

- include/gsl/gsl-lite.hpp
- test/CMakeLists.txt
- test/assert.t.cpp
- test/gsl-lite.t.cpp
- test/gsl-lite.t.hpp
This PR contains some improvements and some fixes mostly relating to contracts and to the new AUDIT and ASSUME contract checking levels.
> Fix several minor issues (mostly with contracts)

- README.md
- include/gsl/gsl-lite.hpp
- test/not_null.t.cpp
Also:
- unit tests from earlier PRs #176 and #192 are added to README (along with tests added in this one)
- fixed -Wunnamed-type-template-args warnings introduced in PR #192
> Fix issue #129: not_null<unique_ptr<T>> is now working as expected

- README.md
- appveyor.yml
(cherry picked from commit 18977bd0d7d97466f10abc2b1676a54f4b8c24ae)
> Add VS 2019 testing in AppVeyor; update testing matrix

- CMakeLists.txt
- README.md
- conanfile.py
- example/cmake-pkg/CMakeLists.txt
- include/gsl/gsl-lite.hpp
- script/update-version.py
I'm not quite ready to produce a release, but I need this version now.
> Bump version number to 0.35.1

- CMakeLists.txt
- README.md
- conanfile.py
- include/gsl/gsl-lite.hpp
- test/gsl-lite.t.cpp
- test/not_null.t.cpp
> Implement `ssize()`, add `gsl_constexpr17/20`, add `gsl_COMPILER_APPLECLANG_VERSION`

- include/gsl/gsl-lite.hpp
> Fix CUDA build

- azure-pipelines.yml
This should make the pipeline run.
> Change Azure Pipelines service endpoint

- .travis.yml
- README.md
- appveyor.yml
- azure-pipelines.yml
> Consolidate CI

- .travis.yml
- README.md
- appveyor.yml
- azure-pipelines.yml
Sorry for the noise, I'll be done very soon.
> Rebalance CI pipelines again

- README.md
- azure-pipelines.yml
- include/gsl/gsl-lite.hpp
- test/util.t.cpp
> Make `narrow<>()` configurable, add `narrow_failfast<>()`

- include/gsl/gsl-lite.hpp
> Fix feature detection for `std::ssize()`

- README.md
- include/gsl/gsl-lite.hpp
- test/issue.t.cpp
Implementing the changes we agreed on in #238.
> Replace SFINAE macros with unified macro `gsl_ENABLE_IF_()`

- include/gsl/gsl-lite.hpp
Fixed typo in feature detection macro.
> Fix condition for gsl_HAVE_FUNCTION_REF_QUALIFIER

- include/gsl/gsl-lite.hpp
- test/not_null.t.cpp
> Fix #258: not_null<T> should not have conversion to bool

- include/gsl/gsl-lite.hpp
> Fix issue #252: build error on AppleClang10 when C++ exceptions are turned off

- README.md
- azure-pipelines.yml
- include/gsl/gsl-lite.hpp
- test/CMakeLists.txt
- test/cuda/CMakeLists.txt
> Add CUDA 11.0, GCC 10, Clang 10, AppleClang 11.0.3 to CI

- README.md
- include/gsl/gsl-lite.hpp
- test/not_null.t.cpp
> Implement `swap()` for `not_null<>`

- include/gsl/gsl-lite.hpp
- test/not_null.t.cpp
> Added std::hash<gsl::not_null<...>>

- include/gsl/gsl-lite.hpp
- test/string_span.t.cpp
> Fix some `zstring_span` consistency issues

- include/gsl/gsl-lite.hpp
- test/cuda/cuda.t.cu
> Implement basic CUDA runtime tests; add more `gsl_api` annotations

- include/gsl/gsl-lite.hpp
> Use nvcc's __builtin_assume(x) for gsl_ASSUME_(x) in device code

- appveyor.yml
- azure-pipelines.yml
- include/gsl/gsl-lite.hpp
They stop working if we don't groom them from time to time.
> Repair the CI pipelines

- README.md
- include/gsl/gsl-lite.hpp
- test/MakeTestTarget.cmake
> Suppress some warnings for Clang and GCC

- README.md
- azure-pipelines.yml
- include/gsl/gsl-lite.hpp
- test/not_null.t.cpp
This addresses issues #233 and #352.
> Support function pointers and `std::function<>` in `not_null<>`
